drop view if exists ATTACHMENT_DICT_V;
  CREATE or REPLACE VIEW PUB_WORK.ATTACHMENT_DICT_V AS 
  WITH GI AS
  /** <SBS_RULE>This will fetch all the catalog general information from the bl_image_data table at bl. For general information attribute1 has value as 'NIS-GI' </SBS_RULE> **/
  (
  SELECT
    IMG_NAME,
    ATTRIBUTE1
  FROM BL.BL_IMAGE_DATA
  WHERE ATTRIBUTE1='NISSAN-GI'
  AND IMG_NAME   IN
    (SELECT MODEL FROM BL.BL_SBS_CATALOG WHERE STATUS='Y'
    )
  ),
  PRICE_ACC_CATALOG_GI AS
  /** <SBS_RULE>This will fetch all the general information for price book and accessory catalog from the bl_image_data table at bl. For general information attribute1 has value as NISSAN_PRICE_BOOK and NISSAN_ACCESSORY_CATALOG </SBS_RULE> **/
  (
  SELECT
    BID.IMG_NAME IMG_NAME,
    BID.ATTRIBUTE1 ATTRIBUTE1,
    BSAT.ATTACHMENT_TITLE ATTACHMENT_TITLE
  FROM BL.BL_IMAGE_DATA BID
  RIGHT OUTER JOIN bl.bl_sbs_attachment_title BSAT
  ON (BSAT.ATTACHMENT_NAME=BID.IMG_NAME)
  WHERE BID.ATTRIBUTE1   IN ('NISSAN_PRICE_BOOK','NISSAN_ACCESSORY_CATALOG')
  ),
  AT_LINKS AS
  /** <SBS_RULE>This will fetch all the Links information from the BL_SBS_EXTERNAL_URL table at bl. </SBS_RULE> **/
  (
  --SELECT URL_NAME,
         --URL_LINK,
        -- GROUP_NAME
  --FROM BL.BL_SBS_EXTERNAL_URL
    SELECT en_us AS URL_NAME
	      ,element_code AS URL_LINK
		  ,'Links' AS GROUP_NAME
	FROM bl.bl_sbs_meta_header 
	WHERE group_name = 'ATTACHMENT_LINK'
  )
SELECT
  /**
  * <SBS_PROLOG>
  * PROJECT:  NISSAN DATA PUBLISHING
  * PURPOSE:  THIS VIEW IS USED IN THE POPULATION OF THE ATTACHMENT_DICT TABLE.
  *
  * PL/SQL OBJECTS USED:
  *   <OBJECT TYPE> - <SCHEMA OWNER> - <OBJECT NAME>
  *===========================================================
  * REVISION HISTORY
  *   REF #  DATE          REVISOR      COMMENT
  *   1      23/07/2015    AB          INITIAL REVISION
  *   2      09/07/2023    DNU         INITIAL
  *===========================================================
  * REVISOR
  *   AB            ABHINAV BANSAL
  *   DNU           DILESH N. UKEY
  *===========================================================
  * </SBS_PROLOG>
  * <SBS_SRCTAB  owner="BL" name="BL_IMAGE_DATA"/
  * <SBS_SRCTAB  owner="BL" name="BL_SBS_CATALOG"/>
  * <SBS_SRCTAB  owner="BL" name="BL_SBS_ATTACHMENT_TITLE"/>
  * <SBS_SRCTAB  owner="BL" name="BL_SBS_EXTERNAL_URL"/>
  * <SBS_DESTTAB owner="CTRG" name="ATTACHMENT_DICT" />
  * <SBS_PRCGRP NAME="LOAD_ATTACHMENTS" SEQ=""/>
  *
  <sbs_rule>attachment_dict_id column from view as AF will create this.</sbs_rule>**/
  --CTRG_SUPPORT.KEY_TO_ID(ATTACHMENT_DICT,DUR_UK) AS ATTACHMENT_DICT_ID,
  DUR_UK,
  BASE_LANG_LOCALE_CODE,
  NULL AS BG_BG,
  NULL AS CS_CZ,
  NULL AS DA_DK,
  NULL AS DE_AT,
  NULL AS DE_CH,
  NULL AS DE_DE,
  NULL AS EL_GR,
  NULL AS EN_GB,
  DESCRIPTION AS EN_US,
  NULL AS ES_ES,
  NULL AS ET_EE,
  NULL AS ES_MX,
  NULL AS FI_FI,
  NULL AS FR_CA,
  NULL AS FR_FR,
  NULL AS HR_HR,
  NULL AS HI_IN,
  NULL AS HU_HU,
  NULL AS IT_IT,
  NULL AS JA_JP,
  NULL AS KO_KR,
  NULL AS LT_LT,
  NULL AS LV_LV,
  NULL AS NL_BE,
  NULL AS NL_NL,
  NULL AS NO_NO,
  NULL AS PL_PL,
  NULL AS PT_BR,
  NULL AS PT_PT,
  NULL AS RO_RO,
  NULL AS RU_RU,
  NULL AS SK_SK,
  NULL AS SL_SI,
  NULL AS SV_SE,
  NULL AS TH_TH,
  NULL AS TR_TR,
  NULL AS UK_UA,
  NULL AS VI_VN,
  NULL AS ZH_CN,
  NULL AS ZH_HK,
  NULL AS ZH_TW,
  NULL AS ZZ_ZZ,
  NULL AS NON_TRANSLATABLE,
  NULL AS URL_BG_BG,
  NULL AS URL_CS_CZ,
  NULL AS URL_DA_DK,
  NULL AS URL_DE_AT,
  NULL AS URL_DE_CH,
  NULL AS URL_DE_DE,
  NULL AS URL_EL_GR,
  NULL AS URL_EN_GB,
  URL AS URL_EN_US,
  NULL AS URL_ES_ES,
  NULL AS URL_ET_EE,
  NULL AS URL_ES_MX,
  NULL AS URL_FI_FI,
  NULL AS URL_FR_CA,
  NULL AS URL_FR_FR,
  NULL AS URL_HR_HR,
  NULL AS URL_HI_IN,
  NULL AS URL_HU_HU,
  NULL AS URL_IT_IT,
  NULL AS URL_JA_JP,
  NULL AS URL_KO_KR,
  NULL AS URL_LT_LT,
  NULL AS URL_LV_LV,
  NULL AS URL_NL_BE,
  NULL AS URL_NL_NL,
  NULL AS URL_NO_NO,
  NULL AS URL_PL_PL,
  NULL AS URL_PT_BR,
  NULL AS URL_PT_PT,
  NULL AS URL_RO_RO,
  NULL AS URL_RU_RU,
  NULL AS URL_SK_SK,
  NULL AS URL_SL_SI,
  NULL AS URL_SV_SE,
  NULL AS URL_TH_TH,
  NULL AS URL_TR_TR,
  NULL AS URL_UK_UA,
  NULL AS URL_VI_VN,
  NULL AS URL_ZH_CN,
  NULL AS URL_ZH_HK,
  NULL AS URL_ZH_TW,
  NULL AS URL_ZZ_ZZ,
  NULL AS URL_NON_TRANSLATABLE,
  FALSE AS ARCHIVABLE_IND,
  TRUE  AS VALID_FOR_MEDIA_IND
   FROM(SELECT 
   CONCAT(GI.IMG_NAME,'|',GI.ATTRIBUTE1)AS DUR_UK,
   'en_US' AS BASE_LANG_LOCALE_CODE,
   GI.IMG_NAME AS DESCRIPTION,
   NULL        AS URL
   FROM GI
   UNION ALL
   SELECT
   CONCAT(PACG.IMG_NAME,'|',PACG.ATTRIBUTE1) AS DUR_UK,
   'en_US' AS BASE_LANG_LOCALE_CODE,
   PACG.ATTACHMENT_TITLE AS DESCRIPTION,
   NULL                  AS URL
   FROM PRICE_ACC_CATALOG_GI PACG
   UNION ALL
   SELECT 
   CONCAT(AL.URL_NAME,'|',AL.GROUP_NAME) AS DUR_UK,
   'en_US' AS BASE_LANG_LOCALE_CODE,
   AL.URL_NAME AS DESCRIPTION,
   AL.URL_LINK AS URL
   FROM AT_LINKS AL
   UNION all
   SELECT 
   '*' AS DUR_UK,
   '*' AS BASE_LANG_LOCALE_CODE,
   NULL AS DESCRIPTION,
   NULL  AS URL   )A
 ;

