drop view if exists bl_f31x1470_catalog_parts_cd5_v;
--------------------------------------------------------
--  DDL for View bl_f31x1470_catalog_parts_cd5_v
--------------------------------------------------------

  CREATE or REPLACE VIEW bl_f31x1470_catalog_parts_cd5_v AS
  WITH
  --  ACTIVE_CATALOGS AS (
  --      /** <SBS_RULE> THIS CLAUSE WILL RESTICT CATALOGS FROM PUBLISHING WHICH ARE NOT ACTIVE  </SBS_RULE>*/
  --      SELECT DISTINCT MODEL
  --      FROM BL_SBS_CATALOG WHERE STATUS = 'Y'
  --  ) ,
  REGEXP_TAB AS
  (SELECT ELEMENT_CODE FROM BL.BL_SBS_META_HEADER BSMH WHERE GROUP_NAME ='REPLACE_NON_PRINTABLE'
  )
SELECT DISTINCT
  /*******************************************************
  <SBS_PROLOG>
  * Project:  NISSAN DATA PUBLISHING
  * Purpose:  This VIEW holds bl_f31x1470_catalog_parts related information.
  *
  * PL/SQL Objects Used:
  * <Object Type> - <Schema  Owner> - <Object Name>
    ===========================================================
    Revision History
    Ref #	Date			     Revisor		Comment
    [ref]	DD-MON-YYYY		[Initials]	[comment]
    1		DD-MON-2016		   NPT			  Initial version
    2		09-OCT-2018		   AR			    REMOVED SPACE FROM PART DESCRIPTION [NSPUB150]
    3		18-SEP-2019		   VG			    CREATED BL_NML_F31X1470_CD1_V from BL_NML_F31X1470_V, Changed source table TO RAW_NML_F31X1470_CD1 FROM RAW_NML_F31X1470.
	4       10-JUL-2023        DU               CREATED VIEW FOR bl_f31x1470_catalog_parts TABLE IN PG
	5       24-AUG-2023        DU               ADDED '|' IN CONCAT OF ROW_HASH COLUMN.
	6       23-DEC-2025        NKM              Move Data Validation from WHERE Clause to AF Check Constraints
    ===========================================================
    Revisor
    *   [initials]		[Full Name]
    *   NPT   				NISSAN PUB TEAM
    *   AR		    		ALISHA RASTOGI
    *   VG		    		VISHAL GARG
	*   DU                  DILESH UKEY
	*   DU                  DILESH UKEY
	*   NKM                 Nitish K Mishra
    ===========================================================
  </SBS_PROLOG>
  <SBS_SRCTAB owner="Work" name="pre_bl_f31x1470_cat_parts_cd5_w" />
  <SBS_DESTTAB owner="BL" name="bl_f31x1470_catalog_parts" />
  <SBS_PRCGRP name="" seq=""/>
  Insert all other tag comments that are relevant
  *********************************************************/
  MODEL_ID_CODE,
  MDL_SER_CODE,
  DESTINATION,
  PART_CODE,
  PART_NUM,
  ADOPT_YR_MON,
  ABOLISH_YR_MON,
  USAGE_CODE,
  CAT_USAGE,
  SPECIFICATION,
  QTY_PER_CAR,
  EXP_RETAIL_PRICE,
  PART_CLASS,
  SALES_CODE,
  NEW_PART_NUM,
  NEW_INTERCHGBLTY,
  NEW_PART_NUM_PRI,
  FIG_NO_NO,
  FIG_NO_DIFF,
  PART_NAME_JPN,
  PART_NAME_ENG,
  PART_NAME_FRE,
  PART_NAME_GER,
  PART_NAME_SPA,
  PERODIC_RPLCMNT_IND,
  TRIM_COLOR,
  BODY_COLOR,
  ADOPT_MC_SWTCH_CODE,
  ABOL_MC_SWTCH_CODE,
  FIG_PAGE,
  APP_IND,
  APPLIED_MOD_BIT_MAP,
  NARROW_DOWN_CODE,
  OP_SYMB,
  SUP_SYMB,
  SPEC_CODE,
  SOURCE_CODE,
  TRANSFER_DATE,
  NOT_OUTPUT_SYMB,
  CTRY_CODE,
  CD_ISSUE_YR_MON,
  MULTI_LANG_SYMB,
  CAT_TYPE_AFTER_CHK,
  AJ_SYMB,
  FILLER,
  SBS_UTIL.GET_HASH_TEXT(CONCAT(MODEL_ID_CODE,'|',MDL_SER_CODE,'|',DESTINATION,'|',PART_CODE,'|',PART_NUM,'|',ADOPT_YR_MON,'|',ABOLISH_YR_MON,'|',USAGE_CODE,'|',CAT_USAGE,'|',SPECIFICATION,'|',QTY_PER_CAR,'|',EXP_RETAIL_PRICE,'|',PART_CLASS,'|',SALES_CODE,'|',NEW_PART_NUM,'|',NEW_INTERCHGBLTY,'|',NEW_PART_NUM_PRI,'|',FIG_NO_NO,'|',FIG_NO_DIFF,'|',PART_NAME_JPN,'|',PART_NAME_ENG,'|',PART_NAME_FRE,'|',PART_NAME_GER,'|',PART_NAME_SPA,'|',PERODIC_RPLCMNT_IND,'|',TRIM_COLOR,'|',BODY_COLOR,'|',ADOPT_MC_SWTCH_CODE,'|',ABOL_MC_SWTCH_CODE,'|',FIG_PAGE,'|',APP_IND,'|',APPLIED_MOD_BIT_MAP,'|',NARROW_DOWN_CODE,'|',OP_SYMB,'|',SUP_SYMB,'|',SPEC_CODE,'|',SOURCE_CODE,'|',TRANSFER_DATE,'|',NOT_OUTPUT_SYMB,'|',CTRY_CODE,'|',CD_ISSUE_YR_MON,'|',MULTI_LANG_SYMB,'|',CAT_TYPE_AFTER_CHK,'|',AJ_SYMB,'|',FILLER)) AS ROW_HASH
  FROM(
  SELECT MODEL_ID_CODE,
  TRIM (REPLACE(V1.MDL_SER_CODE,'/','_')) MDL_SER_CODE,
  DESTINATION,
  TRIM (PART_CODE) PART_CODE,
  TRIM (PART_NUM) PART_NUM,
  CASE
    WHEN ADOPT_YR_MON IS NULL
    THEN '000000'
    WHEN ADOPT_YR_MON ='000000'
    THEN '000000'
    ELSE CONCAT(SUBSTRING(ADOPT_YR_MON,5,2)
         ,SUBSTRING(ADOPT_YR_MON,1,4))
  END AS ADOPT_YR_MON,
  CASE
    WHEN ABOLISH_YR_MON IS NULL
    THEN '999999'
    WHEN ABOLISH_YR_MON ='000000'
    THEN '999999'
    ELSE CONCAT(SUBSTRING(ABOLISH_YR_MON,5,2)
        ,SUBSTRING(ABOLISH_YR_MON,1,4))
  END AS ABOLISH_YR_MON,
  USAGE_CODE,
  CAT_USAGE,
  REGEXP_REPLACE(UPPER(SPECIFICATION) ,RX.ELEMENT_CODE,'') AS SPECIFICATION,
  REPLACE(QTY_PER_CAR,'**','AR') QTY_PER_CAR,
  EXP_RETAIL_PRICE,
  PART_CLASS,
  SALES_CODE,
  REPLACE (NEW_PART_NUM,' ','') NEW_PART_NUM,
  NEW_INTERCHGBLTY,
  NEW_PART_NUM_PRI,
  FIG_NO_NO,
  REPLACE(REPLACE (FIG_NO_DIFF,'*',''),' ','')FIG_NO_DIFF,
  REGEXP_REPLACE(UPPER(PART_NAME_JPN) ,RX.ELEMENT_CODE,'') AS PART_NAME_JPN,
  TRIM(REGEXP_REPLACE(UPPER(PART_NAME_ENG) ,RX.ELEMENT_CODE,'')) AS PART_NAME_ENG, --NSPUB150
  REGEXP_REPLACE(UPPER(PART_NAME_FRE) ,RX.ELEMENT_CODE,'') AS PART_NAME_FRE,
  REGEXP_REPLACE(UPPER(PART_NAME_GER) ,RX.ELEMENT_CODE,'') AS PART_NAME_GER,
  REGEXP_REPLACE(UPPER(PART_NAME_SPA) ,RX.ELEMENT_CODE,'') AS PART_NAME_SPA,
  PERODIC_RPLCMNT_IND,
  TRIM(TRIM_COLOR) TRIM_COLOR,
  BODY_COLOR,
  ADOPT_MC_SWTCH_CODE,
  ABOL_MC_SWTCH_CODE,
  FIG_PAGE,
  APP_IND,
  APPLIED_MOD_BIT_MAP,
  NARROW_DOWN_CODE,
  OP_SYMB,
  SUP_SYMB,
  SPEC_CODE,
  SOURCE_CODE,
  TRANSFER_DATE,
  NOT_OUTPUT_SYMB,
  CTRY_CODE,
  CD_ISSUE_YR_MON,
  MULTI_LANG_SYMB,
  CAT_TYPE_AFTER_CHK,
  AJ_SYMB,
  FILLER
FROM PUB_WORK.pre_bl_f31x1470_cat_parts_cd5_w V1
CROSS JOIN REGEXP_TAB RX
  --inner join ACTIVE_CATALOGS ON V1.MDL_SER_CODE=ACTIVE_CATALOGS.MODEL
)A;
