drop view if exists EIN_NOTE_DICT_V;
CREATE or REPLACE VIEW PUB_WORK.EIN_NOTE_DICT_V AS 
 SELECT
  /**
  * <SBS_PROLOG>
  * PROJECT:  NISSAN DATA PUBLISHING
  * PURPOSE:  THIS VIEW IS USED IN THE POPULATION OF THE CTRG EIN_NOTE_DICT TABLE.
  *
  * PL/SQL OBJECTS USED:
  *   <OBJECT TYPE> - <SCHEMA OWNER> - <OBJECT NAME>
  *===========================================================
  * REVISION HISTORY
  *   REF #  DATE          REVISOR      COMMENT
  *   1      11-MAY-2023    DNU         INITIAL
  *===========================================================
  * REVISOR
  *   DNU           DILESH N. UKEY
  *===========================================================
  * </SBS_PROLOG>
  * <SBS_SRCTAB  owner="BL" name="BL_SBS_META_HEADER"/
  * <SBS_DESTTAB owner="CTRG" name="EIN_NOTE_DICT" />
  * <SBS_PRCGRP NAME="LOAD EIN_NOTE_DICT" SEQ=""/>
  *
  <sbs_rule>EIN_NOTE_DICT_ID column from view as AF will create this.</sbs_rule>**/
  --CTRG_SUPPORT.KEY_TO_ID(EIN_NOTE_DICT,CONCAT(ELEMENT_CODE,'|',ELEMENT_DESC)) AS EIN_NOTE_DICT_ID, 
   CONCAT(ELEMENT_CODE,'|',ELEMENT_DESC) AS DUR_UK,
   'en_US' AS BASE_LANG_LOCALE_CODE,
   NULL AS BG_BG,
   NULL AS CS_CZ,
   NULL AS DA_DK,
   NULL AS DE_AT,
   NULL AS DE_CH,
   NULL AS DE_DE,
   NULL AS EL_GR,
   NULL AS EN_GB,
   ELEMENT_DESC AS EN_US,
   NULL AS ES_ES,
   NULL AS ET_EE,
   NULL AS ES_MX,
   NULL AS FI_FI, 
   NULL AS FR_CA,
   NULL AS FR_FR,
   NULL AS HR_HR,
   NULL AS HI_IN,
   NULL AS HU_HU,
   NULL AS IT_IT,
   NULL AS JA_JP,
   NULL AS KO_KR,
   NULL AS LT_LT,
   NULL AS LV_LV,
   NULL AS NL_BE,
   NULL AS NL_NL,
   NULL AS NO_NO,
   NULL AS PL_PL,
   NULL AS PT_BR,
   NULL AS PT_PT,
   NULL AS RO_RO,
   NULL AS RU_RU,
   NULL AS SK_SK,
   NULL AS SL_SI,
   NULL AS SV_SE,
   NULL AS TH_TH,
   NULL AS TR_TR,
   NULL AS UK_UA,
   NULL AS VI_VN,
   NULL AS ZH_CN,
   NULL AS ZH_HK,
   NULL AS ZH_TW,
   NULL AS ZZ_ZZ,
   NULL AS NON_TRANSLATABLE,
   FALSE AS ARCHIVABLE_IND,
   TRUE  AS VALID_FOR_MEDIA_IND
   FROM BL.BL_SBS_META_HEADER 
   WHERE GROUP_NAME= 'VIN_NOTE' 
   AND ELEMENT_CODE = 'SPCL_VIN_NOTE'
   UNION ALL 
   SELECT
   '*' AS DUR_UK,
   '*' AS BASE_LANG_LOCALE_CODE,
   NULL AS BG_BG,
   NULL AS CS_CZ,
   NULL AS DA_DK,
   NULL AS DE_AT,
   NULL AS DE_CH,
   NULL AS DE_DE,
   NULL AS EL_GR,
   NULL AS EN_GB,
   NULL AS EN_US,
   NULL AS ES_ES,
   NULL AS ET_EE,
   NULL AS ES_MX,
   NULL AS FI_FI, 
   NULL AS FR_CA,
   NULL AS FR_FR,
   NULL AS HR_HR,
   NULL AS HI_IN,
   NULL AS HU_HU,
   NULL AS IT_IT,
   NULL AS JA_JP,
   NULL AS KO_KR,
   NULL AS LT_LT,
   NULL AS LV_LV,
   NULL AS NL_BE,
   NULL AS NL_NL,
   NULL AS NO_NO,
   NULL AS PL_PL,
   NULL AS PT_BR,
   NULL AS PT_PT,
   NULL AS RO_RO,
   NULL AS RU_RU,
   NULL AS SK_SK,
   NULL AS SL_SI,
   NULL AS SV_SE,
   NULL AS TH_TH,
   NULL AS TR_TR,
   NULL AS UK_UA,
   NULL AS VI_VN,
   NULL AS ZH_CN,
   NULL AS ZH_HK,
   NULL AS ZH_TW,
   NULL AS ZZ_ZZ,
   NULL AS NON_TRANSLATABLE,
   FALSE AS ARCHIVABLE_IND,
   TRUE  AS VALID_FOR_MEDIA_IND
   ;