drop view if exists EIN_NOTE_V;

CREATE or REPLACE VIEW PUB_WORK.EIN_NOTE_V AS 
 With DOI AS
  (/** <SBS_RULE> THIS CLAUSE WILL FETCH DATA ORIGIN ID, THIS WILL BE THE ID OF DATA ORIGIN NAMED 'NIS|ALL', FROM TABLE 'DATA_ORIGIN'. </SBS_RULE>*/
   SELECT DATA_ORIGIN_ID
   FROM CTRG_SUPPORT.DATA_ORIGIN
   WHERE DUR_UK = 'NIS|ALL'
  ),
  DT AS
  (/** <SBS_RULE>Display_type_id is selected from Orcl Display_type table where type_name is 'DISPLAY' </SBS_RULE> **/
   SELECT 1 AS DISPLAY_TYPE_ID
  ),
  NT AS
  (/** <SBS_RULE>Note_type_id is selected from Orcl Note_type table where type_name is 'IMPORTANT MESSAGE' </SBS_RULE> **/
  SELECT 2 AS NOTE_TYPE_ID
  ),
  SMH AS
  ( SELECT ELEMENT_CODE,ELEMENT_DESC
    FROM BL.BL_SBS_META_HEADER 
    WHERE GROUP_NAME= 'VIN_NOTE' 
    AND ELEMENT_CODE = 'SPCL_VIN_NOTE'
   )
  SELECT
  /**
  * <SBS_PROLOG>
  * PROJECT:  NISSAN DATA PUBLISHING
  * PURPOSE:  THIS VIEW IS USED IN THE POPULATION OF THE CTRG EIN_NOTE TABLE.
  *
  * PL/SQL OBJECTS USED:
  *   <OBJECT TYPE> - <SCHEMA OWNER> - <OBJECT NAME>
  *===========================================================
  * REVISION HISTORY
  *   REF #  DATE          REVISOR      COMMENT
  *   1      11-MAY-2023    DNU         INITIAL
  *===========================================================
  * REVISOR
  *   DNU           DILESH N. UKEY
  *===========================================================
  * </SBS_PROLOG>
  * <SBS_SRCTAB  owner="CTRG_SUPPORT" name="DATA_ORIGIN"/
  * <SBS_SRCTAB  owner="BL" name="BL_SBS_META_HEADER"/
  * <SBS_DESTTAB owner="CTRG" name="EIN_NOTE" />
  * <SBS_PRCGRP NAME="LOAD_EIN_NOTE" SEQ=""/>
  *
   <sbs_rule>EIN_NOTE_ID column from view as AF will create this.</sbs_rule>**/
  --CTRG_SUPPORT.KEY_TO_ID('EIN_NOTE',DUR_UK) AS EIN_NOTE_ID,
  CONCAT(SMH.ELEMENT_CODE,'|',SMH.ELEMENT_DESC) AS DUR_UK,
  NT.NOTE_TYPE_ID AS NOTE_TYPE,
  COALESCE(ND.DUR_UK_ID ,(SELECT DUR_UK_ID FROM CTRG_SUPPORT.EIN_NOTE_DICT_KEY_IDS WHERE DUR_UK = '*')) AS  EIN_NOTE_DICT_ID,
  SMH.ELEMENT_CODE AS FLEX1,
  SMH.ELEMENT_DESC AS FLEX2,
  NULL AS FLEX3,
  NULL AS FLEX4,
  NULL AS FLEX5,
  NULL AS FLEX6,
  NULL AS FLEX7,
  NULL AS FLEX8,
  NULL AS FLEX9,
  NULL AS FLEX10,
  NULL AS SECURED_ID,
  DOI.DATA_ORIGIN_ID AS DATA_ORIGIN_ID,
  NULL AS NOTE_GROUP_CODE,
  FALSE AS ARCHIVABLE_IND,
  TRUE  AS VALID_FOR_MEDIA_IND,
  DT.DISPLAY_TYPE_ID AS DISPLAY_TYPE,
  NULL::TIMESTAMP WITH TIME ZONE AS EFFECTIVE_DATE,
  NULL::TIMESTAMP WITH TIME ZONE AS EXPIRATION_DATE
  FROM SMH
  CROSS JOIN DOI
  CROSS JOIN DT
  CROSS JOIN NT
  LEFT JOIN CTRG_SUPPORT.EIN_NOTE_DICT_KEY_IDS ND
  ON  CONCAT(SMH.ELEMENT_CODE,'|',SMH.ELEMENT_DESC) = ND.DUR_UK
  ;
  
  
  
  