drop view if exists PART_SUPERSESSION_V;

 CREATE or REPLACE VIEW PUB_WORK.PART_SUPERSESSION_V AS
  WITH DOI AS
  (
  /** <SBS_RULE> THIS CLAUSE WILL FETCH DATA ORIGIN ID, THIS WILL BE THE ID OF DATA ORIGIN NAMED 'NIS|ALL', FROM TABLE 'DATA_ORIGIN' </SBS_RULE>*/
  SELECT DATA_ORIGIN_ID AS DATA_ORIGIN_ID
  FROM CTRG_SUPPORT.DATA_ORIGIN 
  WHERE DUR_UK = 'NIS|ALL'
  ),
  DT AS
  (
  /** <SBS_RULE> THIS CLAUSE WILL FETCH 'DISPLAY_TYPE_ID' HAVING TYPE NAME 'DISPLAY', FROM TABLE 'DISPLAY_TYPE'</SBS_RULE> **/
  SELECT 1 AS  DISPLAY_TYPE_ID
  ),
  SMH AS 
  (
   SELECT ELEMENT_CODE 
   FROM BL.BL_SBS_META_HEADER 
   WHERE group_name = 'PART_SUPERSESSION_DICT'
   ),
   RAW_VA_PARTS AS
   (
    SELECT PART_NO,
           SUBSTRING(PART_NO,1,5)||'-'||SUBSTRING(SUBSTRING(PART_NO,6), 1,  (CASE WHEN STRPOS(SUBSTRING(PART_NO,6),'/')=0 THEN LENGTH(SUBSTRING(PART_NO,6)) ELSE STRPOS(SUBSTRING(PART_NO,6),'/')-1 END)) AS PART_NO_1,
           (CASE WHEN SUBSTRING(PART_NO, (CASE WHEN STRPOS(PART_NO,'/')= 0 
		                                       THEN NULL 
											   ELSE STRPOS(PART_NO,'/')+1 END)) = NULL 
		         THEN NULL 
				 ELSE SUBSTRING(PART_NO,1,5)||'-'||SUBSTRING(PART_NO, ( CASE WHEN STRPOS(PART_NO,'/')=0 
				                                                        THEN NULL 
																		ELSE STRPOS(PART_NO,'/')+1 END))END) AS PART_NO_2,
            VA_PART_NO, 
			PART_NAME, 
			BRAND 
	  FROM BL.BL_VA_PARTS
    ),
 WMP2 AS
    (
    /** <SBS_RULE> THIS CLAUSE WILL FETCH DATA PART NUMBER.THIS WILL BE THE NUMBER OF PART, TAKING ALL DISTINCT VALUES FROM TABLE 'MERGE_PARTS_W' .</SBS_RULE>*/
    SELECT a.FM_PART_NUM,
	       a.PART_NUM
	FROM (SELECT CONCAT(SUBSTRING(PART_NUM,1,5),'-',SUBSTRING(part_num,6)) AS FM_PART_NUM,
                 PART_NUM  AS PART_NUM
            FROM PUB_WORK.MERGE_PARTS_W
           WHERE PART_NUM IS NOT NULL
             AND PART_DESC LIKE '%ASSY%'
           UNION
          SELECT PART AS FM_PART_NUM,
                 REPLACE(PART,'-','') AS PART_NUM
            FROM BL.BL_PRICEBK_NISSAN
           WHERE PART IS NOT NULL
             AND PRTDESC1 LIKE '%ASSY%'
           UNION
           SELECT CONCAT(SUBSTRING(SRVPART,1,5),'-',SUBSTRING(SRVPART,6)) AS FM_PART_NUM,
                  SRVPART AS PART_NUM
            FROM PUB_WORK.SERVFILE_W
           WHERE SRVPART IS NOT NULL
    AND SRVTEXT LIKE '%ASSY%')a
    ),
	
  WMP AS (
    /** <SBS_RULE> THIS CLAUSE WILL FETCH DATA PART NUMBER.THIS WILL BE THE NUMBER OF PART, TAKING ALL DISTINCT VALUES FROM TABLE 'PUB_WORK.MERGE_PARTS_W' .</SBS_RULE>*/
    (SELECT CONCAT(SUBSTRING(PART_NUM,1,5),'-',SUBSTRING(part_num,6)) AS FM_PART_NUM,
            PART_NUM AS PART_NUM
       FROM PUB_WORK.MERGE_PARTS_W
       WHERE PART_NUM IS NOT NULL
      EXCEPT
      SELECT wp.FM_PART_NUM,
	         wp.PART_NUM 
	  FROM WMP2 wp
    ) 
  UNION
    (SELECT PART AS FM_PART_NUM,
            REPLACE(PART,'-','') AS PART_NUM
      FROM  BL.BL_PRICEBK_NISSAN
      WHERE PART IS NOT NULL
      EXCEPT
      SELECT wp.FM_PART_NUM,
	         wp.PART_NUM 
	  FROM WMP2 wp
    )
  UNION
    (SELECT CONCAT(SUBSTRING(SRVPART,1,5),'-',SUBSTRING(SRVPART,6)) AS FM_PART_NUM,
            SRVPART  AS PART_NUM
      FROM PUB_WORK.SERVFILE_W
     WHERE SRVPART IS NOT NULL
     EXCEPT
     SELECT wp.FM_PART_NUM,
	        wp.PART_NUM 
	  FROM WMP2 wp
    )
  UNION
    (
    (
    SELECT PART_NO_1 AS FM_PART_NUM, 
	       REPLACE(PART_NO_1, '-','') AS PART_NUM 
      FROM RAW_VA_PARTS 
	 WHERE PART_NO_1 IS NOT NULL
    UNION
    SELECT PART_NO_2 AS FM_PART_NUM, 
	       REPLACE(PART_NO_2, '-','') AS PART_NUM 
		   FROM RAW_VA_PARTS 
    WHERE PART_NO_2 IS NOT NULL
    )
   /*Code change for second VA part ends*/
    EXCEPT
      SELECT wp.FM_PART_NUM,
	         wp.PART_NUM 
	  FROM WMP2 wp
    )     
    ),
    MERGE_WMP  AS
    (
    SELECT FM_PART_NUM, 
	       PART_NUM 
	 FROM WMP
    UNION
    SELECT FM_PART_NUM, 
	       PART_NUM 
	 FROM WMP2
    ),
    SUPER_PART AS
    (
    SELECT A.PRIMPART AS FM_PART_NUM, REPLACE(A.PRIMPART,'-','') AS PART_NUM from BL.BL_SUPERSN_NISSAN A WHERE NOT EXISTS (SELECT 1 FROM MERGE_WMP B WHERE REPLACE(A.PRIMPART,'-','') = B.PART_NUM)
    UNION
    SELECT A.SUPRPART AS DM_PART_NUM, REPLACE(A.SUPRPART,'-','') AS PART_NUM FROM BL.BL_SUPERSN_NISSAN A WHERE NOT EXISTS (SELECT 1 FROM MERGE_WMP B WHERE REPLACE(A.SUPRPART,'-','') = B.PART_NUM)
    UNION
    SELECT A.NEWPART AS DM_PART_NUM, REPLACE(A.NEWPART,'-','') AS PART_NUM FROM BL.BL_PRICEBK_NISSAN A WHERE  NOT EXISTS (SELECT 1 FROM MERGE_WMP B WHERE REPLACE(A.NEWPART,'-','') = B.PART_NUM) AND NEWPART IS NOT NULL
    ),
    MWMP AS(
    SELECT FM_PART_NUM, PART_NUM FROM MERGE_WMP
    UNION
     SELECT FM_PART_NUM, PART_NUM FROM SUPER_PART
     ),
  PB AS
  ( SELECT PART, 
           NEWPART, 
		   INTERCODE  
	 FROM ( SELECT DISTINCT REPLACE(PRIMPART,'-','')AS PART, 
	               REPLACE(SUPRPART,'-','') AS NEWPART, 
				   INTERCODE 
		      FROM BL.BL_SUPERSN_NISSAN
           UNION ALL
            SELECT DISTINCT REPLACE(PB.PART,'-','') AS PART, 
			       REPLACE(PB.NEWPART,'-','')  AS NEWPART,
				   '1' AS INTERCODE
              FROM BL.BL_PRICEBK_NISSAN PB
             WHERE PB.NEWPART IS NOT NULL
             AND NOT EXISTS(SELECT 1 FROM BL.BL_SUPERSN_NISSAN SS 
			                WHERE REPLACE(PB.PART,'-','')||'|'||REPLACE(PB.NEWPART,'-','') = REPLACE(SS.PRIMPART,'-','')||'|'||REPLACE(SS.SUPRPART,'-',''))
           )P 
	 INNER JOIN  MWMP
     ON (P.PART = MWMP.PART_NUM)
  ),
 PSD as
     (SELECT REPLACE(SUP.PRIMPART,'-','') AS OLD_PART,
             REPLACE(PRC.NEWPART,'-','')  AS NEW_PART,
             CASE WHEN SMH.ELEMENT_CODE is null 
			      THEN 'else' 
				  ELSE SMH.ELEMENT_CODE end as ELEMENT_CODE
       FROM bl.BL_SUPERSN_NISSAN SUP
       JOIN bl.BL_PRICEBK_NISSAN PRC
        ON (SUP.PRIMPART   = PRC.PART)  
      LEFT JOIN SMH
        ON SUP.INTERCODE = SMH.ELEMENT_CODE
     WHERE PRC.NEWPART IS NOT NULL
  UNION
     SELECT REPLACE(SUP.PRIMPART,'-','') AS OLD_PART,
            REPLACE(SUP.SUPRPART,'-','')  AS NEW_PART,
            case when SMH.ELEMENT_CODE is null 
			     then 'else' else SMH.ELEMENT_CODE end as ELEMENT_CODE
       FROM bl.BL_SUPERSN_NISSAN SUP
       LEFT JOIN SMH
       ON SUP.INTERCODE=SMH.ELEMENT_CODE
     ),
  DEFAULT_ENTRY as
  (SELECT DUR_UK_ID 
   FROM CTRG_SUPPORT.PART_SUPERSESSION_DICT_KEY_IDS 
   WHERE DUR_UK ='*')  
SELECT
  /**
  * <SBS_PROLOG>
  * PROJECT:  NISSAN DATA PUBLISHING
  * PURPOSE:  THIS VIEW IS USED IN THE POPULATION OF THE PART SUPERSESSION TABLE.
  *
  * PL/SQL OBJECTS USED:
  *   <OBJECT TYPE> - <SCHEMA OWNER> - <OBJECT NAME>
  *===========================================================
  * REVISION HISTORY
  *   REF #  DATE          REVISOR      COMMENT
  *   1      02-09-2015    NS          INITIAL REVISION
  *   2      25-04-2017    MG          ADDED DISTINCT IN PB CLAUSE AGAINST JIRA NSPUB-47
  *   2      24-05-2017    NK          CHANGES PB CLAUSE TO INCLUDE PARTS FROM BL_SUPERSN_NISSAN, AGAINST JIRA NSPUB-55. Changed commenting of PB Clause.Also included
  *   3      04-05-2023    DNU         MIGRATE ORCL VIEW TO PG 
  *===========================================================
  * REVISOR
  *   NS            NISHANT SONI
  *   MG            MAYANK GUPTA
  *   NK            NISHANT KARIYA
  *   DNU           DILESH N. UKEY
  *===========================================================
  * </SBS_PROLOG>
  * <SBS_SRCTAB  owner="CTRG_SUPPORT" name="DATA_ORIGIN"/>
  * <SBS_SRCTAB owner="BL" name="BL_PRICEBK_NISSAN" />
  * <SBS_SRCTAB owner="BL" name="BL_SUPERSN_NISSAN" />
  * <SBS_DESTTAB owner="CTRG" name="PART_SUPERSESSION" />
  * <SBS_PRCGRP name="LOAD_LOWER_NAVIGATION" seq=""/>
  *
  **<sbs_rule>part_supersession_id column from view as AF will create this.</sbs_rule>**/
--ctrg_support.key_to_id('part_supersession',CONCAT(KP.DUR_UK,'|',KP.DUR_UK,'|',KPN.DUR_UK)) as part_supersession_id,
      KP.DUR_UK_ID   AS PART_ID,
      KP.DUR_UK_ID   AS OLD_PART_ID,
      1 AS PART_SUPERSESSION_TYPE,
      CONCAT(KP.DUR_UK,'|',KP.DUR_UK,'|',KPN.DUR_UK) AS DUR_UK,
      (CASE WHEN PB.INTERCODE = '1' THEN 1::bool
            WHEN PB.INTERCODE = '2' THEN 0::bool  
		    ELSE 1::bool
        END)   AS FORWARD_ONLY,
       '0000000001'  AS SORT_SEQ,
       COALESCE(PSSD.DUR_UK_ID,DE.DUR_UK_ID) AS PART_SUPERSESSION_DICT_ID,
       NULL  AS PRICE_BOOK_ID,
       NULL::int  AS PART_SUPERSESSION_GROUP_ID,
       FALSE  AS OLD_PART_DISCON_BY_CONTEXT,
       FALSE  AS NEW_PART_DISCON_BY_CONTEXT,
       KP.DUR_UK  AS FLEX1,
       KP.DUR_UK  AS FLEX2,
       KPN.DUR_UK AS FLEX3,
       NULL       AS FLEX4,
       NULL       AS FLEX5,
       NULL       AS FLEX6,
       NULL       AS FLEX7,
       NULL       AS FLEX8,
       NULL       AS FLEX9,
       NULL       AS FLEX10,
       NULL       AS PART_SUPERSESSION_SET,
       NULL::timestamp with time zone  AS EFFECTIVE_DATE,
       NULL       AS QUANTITY,
       DOI.DATA_ORIGIN_ID  AS DATA_ORIGIN_ID,
       KPN.DUR_UK_ID       AS NEW_PART_ID,
       NULL::int           AS ROW_AE_ID,
       FALSE               AS ARCHIVABLE_IND,
       TRUE                AS VALID_FOR_MEDIA_IND,
       NULL                AS PART_SUPERSESSION_SET_OPERAND,
       DT.DISPLAY_TYPE_ID  AS DISPLAY_TYPE
  FROM DOI
  CROSS JOIN DT
  CROSS JOIN PB
  CROSS JOIN DEFAULT_ENTRY DE
  INNER JOIN CTRG_SUPPORT.PART_KEY_IDS KP
  ON PB.PART = KP.DUR_UK
  INNER JOIN CTRG_SUPPORT.PART_KEY_IDS KPN
  ON PB.NEWPART = KPN.DUR_UK
  LEFT OUTER JOIN PSD
  ON PB.PART = PSD.OLD_PART 
  AND PB.NEWPART = PSD.NEW_PART
  LEFT OUTER JOIN CTRG_SUPPORT.PART_SUPERSESSION_DICT_KEY_IDS PSSD
  ON PSD.ELEMENT_CODE = PSSD.DUR_UK;
