delete from  bl.bl_sbs_oct_meta_tables;
INSERT INTO bl.bl_sbs_oct_meta_tables (schema_name, table_name, exclude_columns, to_be_compare) VALUES('ctrg', 'business_region', NULL, 'Y');
INSERT INTO bl.bl_sbs_oct_meta_tables (schema_name, table_name, exclude_columns, to_be_compare) VALUES('ctrg', 'business_region_dict', NULL, 'Y');
INSERT INTO bl.bl_sbs_oct_meta_tables (schema_name, table_name, exclude_columns, to_be_compare) VALUES('ctrg', 'config', NULL, 'Y');
INSERT INTO bl.bl_sbs_oct_meta_tables (schema_name, table_name, exclude_columns, to_be_compare) VALUES('ctrg', 'dataset_property', NULL, 'Y');
INSERT INTO bl.bl_sbs_oct_meta_tables (schema_name, table_name, exclude_columns, to_be_compare) VALUES('ctrg', 'dataset_resource', NULL, 'Y');
INSERT INTO bl.bl_sbs_oct_meta_tables (schema_name, table_name, exclude_columns, to_be_compare) VALUES('ctrg', 'feature_map', NULL, 'Y');
INSERT INTO bl.bl_sbs_oct_meta_tables (schema_name, table_name, exclude_columns, to_be_compare) VALUES('ctrg', 'filter_control', NULL, 'Y');
INSERT INTO bl.bl_sbs_oct_meta_tables (schema_name, table_name, exclude_columns, to_be_compare) VALUES('ctrg', 'function_data', NULL, 'Y');
INSERT INTO bl.bl_sbs_oct_meta_tables (schema_name, table_name, exclude_columns, to_be_compare) VALUES('ctrg', 'make', NULL, 'Y');
INSERT INTO bl.bl_sbs_oct_meta_tables (schema_name, table_name, exclude_columns, to_be_compare) VALUES('ctrg', 'make_dict', NULL, 'Y');
INSERT INTO bl.bl_sbs_oct_meta_tables (schema_name, table_name, exclude_columns, to_be_compare) VALUES('ctrg', 'oem', NULL, 'Y');
INSERT INTO bl.bl_sbs_oct_meta_tables (schema_name, table_name, exclude_columns, to_be_compare) VALUES('ctrg', 'support', NULL, 'Y');
INSERT INTO bl.bl_sbs_oct_meta_tables (schema_name, table_name, exclude_columns, to_be_compare) VALUES('ctrg', 'vin_decode_attribute', NULL, 'Y');
INSERT INTO bl.bl_sbs_oct_meta_tables (schema_name, table_name, exclude_columns, to_be_compare) VALUES('ctrg', 'vin_decode_group', NULL, 'Y');
INSERT INTO bl.bl_sbs_oct_meta_tables (schema_name, table_name, exclude_columns, to_be_compare) VALUES('ctrg', 'vin_decode_group_dict', NULL, 'Y');
INSERT INTO bl.bl_sbs_oct_meta_tables (schema_name, table_name, exclude_columns, to_be_compare) VALUES('ctrg', 'vin_decode_group_member', NULL, 'Y');
INSERT INTO bl.bl_sbs_oct_meta_tables (schema_name, table_name, exclude_columns, to_be_compare) VALUES('ctrg_support', 'data_origin', NULL, 'Y');
INSERT INTO bl.bl_sbs_oct_meta_tables (schema_name, table_name, exclude_columns, to_be_compare) VALUES('ctrg_support', 'data_source', NULL, 'Y');
INSERT INTO bl.bl_sbs_oct_meta_tables (schema_name, table_name, exclude_columns, to_be_compare) VALUES('ctrg_support', 'dataset_securable', NULL, 'Y');
INSERT INTO bl.bl_sbs_oct_meta_tables (schema_name, table_name, exclude_columns, to_be_compare) VALUES('ctrg_support', 'oem', NULL, 'Y');
INSERT INTO bl.bl_sbs_oct_meta_tables (schema_name, table_name, exclude_columns, to_be_compare) VALUES('ctrg_support', 'sbs_filter_type', NULL, 'Y');
INSERT INTO bl.bl_sbs_oct_meta_tables (schema_name, table_name, exclude_columns, to_be_compare) VALUES('ctrg_support', 'sbs_hosting_table_partition_rules', NULL, 'Y');
INSERT INTO bl.bl_sbs_oct_meta_tables (schema_name, table_name, exclude_columns, to_be_compare) VALUES('ctrg_support', 'sbs_property', NULL, 'Y');
INSERT INTO bl.bl_sbs_oct_meta_tables (schema_name, table_name, exclude_columns, to_be_compare) VALUES('ctrg_support', 'sbs_prosynch_partitionid_xref', NULL, 'Y');
INSERT INTO bl.bl_sbs_oct_meta_tables (schema_name, table_name, exclude_columns, to_be_compare) VALUES('ctrg_support', 'sbs_schema_target_type_x', NULL, 'Y');
INSERT INTO bl.bl_sbs_oct_meta_tables (schema_name, table_name, exclude_columns, to_be_compare) VALUES('ctrg_support', 'sbs_status', NULL, 'Y');
INSERT INTO bl.bl_sbs_oct_meta_tables (schema_name, table_name, exclude_columns, to_be_compare) VALUES('ctrg_support', 'ssw_license_ss', NULL, 'Y');
INSERT INTO bl.bl_sbs_oct_meta_tables (schema_name, table_name, exclude_columns, to_be_compare) VALUES('ctrg_support', 'ssw_subset_id_ss', NULL, 'Y');
INSERT INTO bl.bl_sbs_oct_meta_tables (schema_name, table_name, exclude_columns, to_be_compare) VALUES('pub_admin', 'aat_app_access_types_t', NULL, 'Y');
INSERT INTO bl.bl_sbs_oct_meta_tables (schema_name, table_name, exclude_columns, to_be_compare) VALUES('pub_admin', 'dr_datasrc_t', 'datasrc_id', 'Y');
INSERT INTO bl.bl_sbs_oct_meta_tables (schema_name, table_name, exclude_columns, to_be_compare) VALUES('pub_admin', 'dr_datasrclctn_t', NULL, 'Y');
INSERT INTO bl.bl_sbs_oct_meta_tables (schema_name, table_name, exclude_columns, to_be_compare) VALUES('pub_admin', 'dr_prvdr_t', NULL, 'Y');
INSERT INTO bl.bl_sbs_oct_meta_tables (schema_name, table_name, exclude_columns, to_be_compare) VALUES('pub_admin', 'pba_param_t', NULL, 'Y');
INSERT INTO bl.bl_sbs_oct_meta_tables (schema_name, table_name, exclude_columns, to_be_compare) VALUES('ssctrg', 'ssw_oem_config', NULL, 'Y');

Analyse verbose bl.bl_sbs_oct_meta_tables ;