<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	
	<groupId>com.snapon.sbs</groupId>
	<artifactId>NG_NISSAN</artifactId>
	<version>3.4.4.1</version>
	<packaging>pom</packaging>
	
	
	<parent>
		<groupId>com.snapon.sbs</groupId>
		<artifactId>pub-dev-pom</artifactId>
		<version>1.0.0</version>
	</parent>
  
	<properties>
			<artifactory.location>http://artifactory-sbs.snaponglobal.com:8080/artifactory</artifactory.location>
	</properties>
	
	
	<build>
		<finalName>${project.version}</finalName>
		
		<resources>
			<resource>
				<directory>java/src/main/resources</directory>
				<filtering>true</filtering>
			</resource>
		</resources>
	
		<plugins>
			<!-- Use the Ant plugin to create autodeploy ZIP with target layout, to avoid manual deployment steps -->
			<plugin>
				<artifactId>maven-antrun-plugin</artifactId>
				<version>1.7</version>
				<executions>
										
					<execution>
						<id>attach-artifact-1</id>
						<phase>package</phase>
						<goals>
							<goal>run</goal>
						</goals>
						
						<configuration>
							<target>
								<echo message="Creating Zip file for PostgreSQL ..."/>
								<property name="zipDir" value="${project.build.directory}/postgres-zips"/>
								<property name="zipFile" value="${project.build.directory}/postgres.zip"/>
								<delete dir="${zipDir}" quiet="true"/>
								<mkdir dir="${zipDir}/postgres"/>								
								<copy todir="${zipDir}/postgres">
									<!--<fileset dir="NisNG_PostGres" includes="**/*.sql"/>-->
									<fileset dir="postgres" includes="**/*.*"/>
								</copy>								
								<zip destfile="${zipFile}">
									<!-- Use zipfileset to take advantage of the mode attributes -->
									<zipfileset dir="." includes="${version}" fullpath="${version}" dirmode="755"/>
									<zipfileset dir="${zipDir}" includes="postgres" fullpath="postgres" dirmode="755"/>
									<zipfileset dir="${zipDir}/postgres" prefix="postgres" dirmode="777" filemode="755"/> 
								</zip>
								<attachartifact file="${zipFile}" classifier="postgres" type="zip"/></target>
						</configuration>
					</execution>
					
					<execution>
						<id>attach-artifact-2</id>
						<phase>package</phase>
						<goals>
							<goal>run</goal>
						</goals>
						<configuration>
							<target>
								<echo message="Creating Zip file for Playbook ..."/>
								<property name="zipDir" value="${project.build.directory}/playbook-zips/${version}"/>
								<property name="zipFile" value="${project.build.directory}/playbook.zip"/>
								<delete dir="${zipDir}" quiet="true"/>
								<mkdir dir="${zipDir}/playbook"/>								
								<copy todir="${zipDir}/playbook">
									<fileset dir="playbook" includes="**/*.*"/>
								</copy>
								<zip destfile="${zipFile}">
									<!-- Use zipfileset to take advantage of the mode attributes -->
									<zipfileset dir="." includes="${version}" fullpath="${version}" dirmode="755"/>
									<zipfileset dir="${zipDir}" includes="playbook" fullpath="playbook" dirmode="755"/>
									<zipfileset dir="${zipDir}/playbook" prefix="playbook" dirmode="777" filemode="755"/> 
								</zip>
								<attachartifact file="${zipFile}" classifier="playbook" type="zip"/></target>
						</configuration>
					</execution>
					
						
					<execution>
						<id>attach-artifact-3</id>
						<phase>package</phase>
						<goals>
							<goal>run</goal>
						</goals>
						<configuration>
							<target>
								<echo message="Creating Zip file for AF Objects ..."/>
								<property name="zipDir" value="${project.build.directory}/af-zips/${version}"/>
								<property name="zipFile" value="${project.build.directory}/af.zip"/>
								<delete dir="${zipDir}" quiet="true"/>
								<mkdir dir="${zipDir}/af"/>								
								<copy todir="${zipDir}/af">
									<fileset dir="af" includes="**/*.*"/>
								</copy>
								<zip destfile="${zipFile}">
									<!-- Use zipfileset to take advantage of the mode attributes -->
									<zipfileset dir="." includes="${version}" fullpath="${version}" dirmode="755"/>
									<zipfileset dir="${zipDir}" includes="af" fullpath="af" dirmode="755"/>
									<zipfileset dir="${zipDir}/af" prefix="af" dirmode="777" filemode="755"/> 
								</zip>
								<attachartifact file="${zipFile}" classifier="af" type="zip"/></target>
						</configuration>
					</execution>
						
										
				</executions>
			</plugin>
		</plugins>
	</build>
</project>