
INSERT INTO pub_admin.dr_datasrc_t
(datasrc_id, prvdr_id, datasrclctn_id, cntng_datasrc_id, datasrc_nm, datasrc_dsc, datasrc_ntfy_email_addr_txt, datasrc_file_name_ptrn_txt, datasrc_file_cnt, datasrc_max_wait_hours_qty, datasrc_sort_txt, datasrc_file_path_txt, datasrc_file_mode_cd, datasrc_after_rcpt_actn_cd, datasrc_loadplan_name_txt, loadplan_warning_allowed, is_file_optional, do_not_process_ind, ds_processing_seq, datasrc_zipfile_passwd, last_file_not_found_err_ts, max_hrs_since_last_file_qty, datasrc_file_max_byte_qty, datasrc_suffix_nm, datasrc_file_min_byte_qty, datasrc_xslt, http_adapter_nm, new_file_rqrd_ind, uniq_file_name_flg, datasrc_error_loadplan_nm, ignore_uniqueness_ind, retain_days_qty, dos_to_unix_flag, src_stage_file_encoding, trg_stage_file_encoding, excel_replace_new_line, difrnt_src_fl_encodng_fail_flg, ignore_case_flg, dbf_encoding, trgt_file_nm_suffix, ignore_archive_duplicates, excel_find_pattern, excel_replace_pattern, rcrd_create_ts, rcrd_create_user_id, rcrd_create_ip, rcrd_updt_ts, rcrd_updt_user_id, rcrd_updt_ip, min_heapsize, max_heapsize)
VALUES(983, 101, 106, NULL, 'OCT_DDL_LOADING_TIER1', 'To Load Object DDL and Metadata in dev for comparision', NULL, '^.*oct_ddl_export.*\.(csv|gz)$', NULL, '0', 'sort()', '/F/Ford/FRDCornerstone/EPO/OCT/TIER1', 'DELTA', 'RENAME', 'oct_ddl_tier1_wf', 'Y', 'N', 'N', 0, NULL, NULL, '0', NULL, NULL, NULL, NULL, NULL, 'Y', 0, NULL, 'N', 90, 'N', NULL, NULL, NULL, 'N', 'N', NULL, NULL, 'Y', NULL, NULL, '2024-04-28 10:32:34.730', 'pub_admin', '172.22.214.178/32', '2024-06-03 15:27:03.043', 'pub_admin', '172.22.214.246/32', NULL, NULL) on conflict (datasrc_id) do nothing;
INSERT INTO pub_admin.dr_datasrc_t
(datasrc_id, prvdr_id, datasrclctn_id, cntng_datasrc_id, datasrc_nm, datasrc_dsc, datasrc_ntfy_email_addr_txt, datasrc_file_name_ptrn_txt, datasrc_file_cnt, datasrc_max_wait_hours_qty, datasrc_sort_txt, datasrc_file_path_txt, datasrc_file_mode_cd, datasrc_after_rcpt_actn_cd, datasrc_loadplan_name_txt, loadplan_warning_allowed, is_file_optional, do_not_process_ind, ds_processing_seq, datasrc_zipfile_passwd, last_file_not_found_err_ts, max_hrs_since_last_file_qty, datasrc_file_max_byte_qty, datasrc_suffix_nm, datasrc_file_min_byte_qty, datasrc_xslt, http_adapter_nm, new_file_rqrd_ind, uniq_file_name_flg, datasrc_error_loadplan_nm, ignore_uniqueness_ind, retain_days_qty, dos_to_unix_flag, src_stage_file_encoding, trg_stage_file_encoding, excel_replace_new_line, difrnt_src_fl_encodng_fail_flg, ignore_case_flg, dbf_encoding, trgt_file_nm_suffix, ignore_archive_duplicates, excel_find_pattern, excel_replace_pattern, rcrd_create_ts, rcrd_create_user_id, rcrd_create_ip, rcrd_updt_ts, rcrd_updt_user_id, rcrd_updt_ip, min_heapsize, max_heapsize)
VALUES(984, 101, 106, NULL, 'OCT_DDL_LOADING_TIER2', 'To Load Object DDL and Metadata in dev for comparision', NULL, '^.*oct_ddl_export.*\.(csv|gz)$', NULL, '0', 'sort()', '/F/Ford/FRDCornerstone/EPO/OCT/TIER2', 'DELTA', 'RENAME', 'oct_ddl_tier2_wf', 'Y', 'N', 'N', 0, NULL, NULL, '0', NULL, NULL, NULL, NULL, NULL, 'Y', 0, NULL, 'N', 90, 'N', NULL, NULL, NULL, 'N', 'N', NULL, NULL, 'Y', NULL, NULL, '2024-05-01 22:39:25.606', 'pub_admin', '172.22.172.93/32', '2024-06-03 15:27:15.715', 'pub_admin', '172.22.214.246/32', NULL, NULL) on conflict (datasrc_id) do nothing;
INSERT INTO pub_admin.dr_datasrc_t
(datasrc_id, prvdr_id, datasrclctn_id, cntng_datasrc_id, datasrc_nm, datasrc_dsc, datasrc_ntfy_email_addr_txt, datasrc_file_name_ptrn_txt, datasrc_file_cnt, datasrc_max_wait_hours_qty, datasrc_sort_txt, datasrc_file_path_txt, datasrc_file_mode_cd, datasrc_after_rcpt_actn_cd, datasrc_loadplan_name_txt, loadplan_warning_allowed, is_file_optional, do_not_process_ind, ds_processing_seq, datasrc_zipfile_passwd, last_file_not_found_err_ts, max_hrs_since_last_file_qty, datasrc_file_max_byte_qty, datasrc_suffix_nm, datasrc_file_min_byte_qty, datasrc_xslt, http_adapter_nm, new_file_rqrd_ind, uniq_file_name_flg, datasrc_error_loadplan_nm, ignore_uniqueness_ind, retain_days_qty, dos_to_unix_flag, src_stage_file_encoding, trg_stage_file_encoding, excel_replace_new_line, difrnt_src_fl_encodng_fail_flg, ignore_case_flg, dbf_encoding, trgt_file_nm_suffix, ignore_archive_duplicates, excel_find_pattern, excel_replace_pattern, rcrd_create_ts, rcrd_create_user_id, rcrd_create_ip, rcrd_updt_ts, rcrd_updt_user_id, rcrd_updt_ip, min_heapsize, max_heapsize)
VALUES(985, 101, 106, NULL, 'OCT_SCRIPT_LOADING_TIER1', 'To Load scripts in dev for comparision', NULL, '^.*oct_script_export.*\.(csv|gz)$', NULL, '0', 'sort()', '/F/Ford/FRDCornerstone/EPO/OCT/TIER1', 'DELTA', 'RENAME', 'oct_ddl_tier1_wf', 'Y', 'N', 'N', 0, NULL, NULL, '0', NULL, NULL, NULL, NULL, NULL, 'Y', 0, NULL, 'N', 90, 'N', NULL, NULL, NULL, 'N', 'N', NULL, NULL, 'Y', NULL, NULL, '2024-05-30 18:50:58.335', 'pub_admin', '172.22.214.68/32', '2024-06-03 15:26:35.169', 'pub_admin', '172.22.214.246/32', NULL, NULL) on conflict (datasrc_id) do nothing;
INSERT INTO pub_admin.dr_datasrc_t
(datasrc_id, prvdr_id, datasrclctn_id, cntng_datasrc_id, datasrc_nm, datasrc_dsc, datasrc_ntfy_email_addr_txt, datasrc_file_name_ptrn_txt, datasrc_file_cnt, datasrc_max_wait_hours_qty, datasrc_sort_txt, datasrc_file_path_txt, datasrc_file_mode_cd, datasrc_after_rcpt_actn_cd, datasrc_loadplan_name_txt, loadplan_warning_allowed, is_file_optional, do_not_process_ind, ds_processing_seq, datasrc_zipfile_passwd, last_file_not_found_err_ts, max_hrs_since_last_file_qty, datasrc_file_max_byte_qty, datasrc_suffix_nm, datasrc_file_min_byte_qty, datasrc_xslt, http_adapter_nm, new_file_rqrd_ind, uniq_file_name_flg, datasrc_error_loadplan_nm, ignore_uniqueness_ind, retain_days_qty, dos_to_unix_flag, src_stage_file_encoding, trg_stage_file_encoding, excel_replace_new_line, difrnt_src_fl_encodng_fail_flg, ignore_case_flg, dbf_encoding, trgt_file_nm_suffix, ignore_archive_duplicates, excel_find_pattern, excel_replace_pattern, rcrd_create_ts, rcrd_create_user_id, rcrd_create_ip, rcrd_updt_ts, rcrd_updt_user_id, rcrd_updt_ip, min_heapsize, max_heapsize)
VALUES(986, 101, 106, NULL, 'OCT_SCRIPT_LOADING_TIER2', 'To Load scripts in dev for comparision', NULL, '^.*oct_script_export.*\.(csv|gz)$', NULL, '0', 'sort()', '/F/Ford/FRDCornerstone/EPO/OCT/TIER2', 'DELTA', 'RENAME', 'oct_ddl_tier2_wf', 'Y', 'N', 'N', 0, NULL, NULL, '0', NULL, NULL, NULL, NULL, NULL, 'Y', 0, NULL, 'N', 90, 'N', NULL, NULL, NULL, 'N', 'N', NULL, NULL, 'Y', NULL, NULL, '2024-05-30 18:50:58.335', 'pub_admin', '172.22.214.68/32', '2024-06-03 15:26:11.325', 'pub_admin', '172.22.214.246/32', NULL, NULL) on conflict (datasrc_id) do nothing;

-- datasrc_file_path_txt>> select pub_admin.get_parameter('PBAEPORootPath')||'OCT/TIER1')
-- datasrc_file_path_txt>> select pub_admin.get_parameter('PBAEPORootPath')||'OCT/TIER2')

Analyse verbose pub_admin.dr_datasrc_t;