---
- name: NIS_MASTER_SCRIPT_3.4.4.0
  hosts: PBA_Servers
  gather_facts: true
  
  vars_files:
    - "/opt/ctol/Current_Version/adt_version.yml"
    - "/opt/ctol/AutomatedDeploymentTool/ADT_{{ use_adt_version|regex_replace('\"', '')|regex_replace(\"'\", '')|trim if (use_adt_version is defined and use_adt_version|trim != '') else current_adt_version }}/Config/adt_global.config"
  
  vars: 
    add_to_recepient_list:
      - nitish.k.mishra@snapon.com
      - chandan.bhatia@snapon.com      
      
    ignore_config_mail_to_list: true
    
    ################################################################################################################
    #
    # Created By: Nitish Kumar Mishra
    # Created On: 25 DEC 2025
    #
    # Purpose: Master script which is used for AF&DB Object Deployment at Upper Tier.
    #
    ################################################################################################################
    
    artifactory_url: "{% if version is search('SNAPSHOT') %}{{ artifactory_snaphot_base_url_global }}{% else %}{{ artifactory_base_url_global }}{% endif %}"

    cmd_list:      
      - {"cmd": "run_psql", "source": "ARTIFACTORY", "zip_path": "/NG_NISSAN/{{ version }}/NG_NISSAN-{{ version }}-postgres.zip", "file_path": "/postgres/master_script/NG_NIS_BL_MASTER_SCRIPT_3.4.4.0.sql", "as_user": "bl"} 
      - {"cmd": "run_psql", "source": "ARTIFACTORY", "zip_path": "/NG_NISSAN/{{ version }}/NG_NISSAN-{{ version }}-postgres.zip", "file_path": "/postgres/master_script/NG_NIS_CTRG_MASTER_SCRIPT_3.4.4.0.sql", "as_user": "ctrg"} 
      - {"cmd": "run_psql", "source": "ARTIFACTORY", "zip_path": "/NG_NISSAN/{{ version }}/NG_NISSAN-{{ version }}-postgres.zip", "file_path": "/postgres/master_script/NG_NIS_PUB_ADMIN_MASTER_SCRIPT_3.4.4.0.sql", "as_user": "pub_admin"}
      - {"cmd": "run_psql", "source": "ARTIFACTORY", "zip_path": "/NG_NISSAN/{{ version }}/NG_NISSAN-{{ version }}-postgres.zip", "file_path": "/postgres/master_script/NG_NIS_PUB_WORK_MASTER_SCRIPT_3.4.4.0.sql", "as_user": "pub_work"} 
      - {"cmd": "run_psql", "source": "ARTIFACTORY", "zip_path": "/NG_NISSAN/{{ version }}/NG_NISSAN-{{ version }}-af.zip", "file_path": "/af/master_script/NG_NIS_AF_MASTER_SCRIPT_3.4.4.0.sql", "as_user": "pub_work"}       
      - {"cmd": "run_psql", "source": "ARTIFACTORY", "zip_path": "/NG_NISSAN/{{ version }}/NG_NISSAN-{{ version }}-af.zip", "file_path": "/af/master_script/NG_NIS_AF_REMOVE_SCRIPT_3.4.4.0.sql", "as_user": "af_repo"}
      
  tasks:
    
    - name: start processing 
      include_tasks: "{{ adt_code_path }}/adt_initiator.yml"