---
- name: NIS_UNZIP_SCRIPTS_MASTER_3.4.4.0
  hosts: PBA_Servers
  gather_facts: true
  
  vars_files:
    - "/opt/ctol/Current_Version/adt_version.yml"
    - "/opt/ctol/AutomatedDeploymentTool/ADT_{{ use_adt_version|regex_replace('\"', '')|regex_replace(\"'\", '')|trim if (use_adt_version is defined and use_adt_version|trim != '') else current_adt_version }}/Config/adt_global.config"
  
  vars: 
    add_to_recepient_list:
      - nitish.k.mishra@snapon.com
      - chandan.bhatia@snapon.com  

    ignore_config_mail_to_list: true
    
    artifactory_url: "{% if version is search('SNAPSHOT') %}{{ artifactory_snaphot_base_url_global }}{% else %}{{ artifactory_base_url_global }}{% endif %}"

    pba_env_root_path: "/N/Nissan/NISCornerstone/1.0.0.0"
    
    ################################################################################################################
    #
    # Created By: Nitish Kumar Mishra
    # Created On: 02 Feb 2026
    #
    # Purpose: Master script to unzip ADC and other Script at pubapp server.
    #
    ################################################################################################################


    cmd_list:
      #Check if DIR exists
      - {"cmd": "stat", "target": "HOST_DIR","target_path": "{{ pba_env_root_path }}/app", "not_exist": "fail"}
      #If dir is missing then first execute directory creation Python Script
      
      - {"cmd": "unzip", "source": "ARTIFACTORY", "full_zip_path": "", "zip_path": "/NG_NISSAN/{{ version }}/NG_NISSAN-{{ version }}-linux.zip", "target": "", "target_path": "{{ pba_env_root_path }}/app"}
      
     #Permissions to DIR
      - {"cmd": "chmod", "permissions": "775", "target": "HOST_DIR", "target_type": "DIR", "target_path": "{{ pba_env_root_path }}/app/script"}
     
     #Permissions to DIR and all its contents
      - {"cmd": "chmod", "permissions": "775", "target": "HOST_DIR", "target_type": "DIR_TREE", "target_path": "{{ pba_env_root_path }}/app/script/Images"}
    
     #dos2unix
      - {"cmd": "dos2unix", "source": "HOST_DIR", "file_path": "{{ pba_env_root_path }}/app/script/Images/archive_images.sh"}
      - {"cmd": "dos2unix", "source": "HOST_DIR", "file_path": "{{ pba_env_root_path }}/app/script/Images/call_ipp.sh"}
      - {"cmd": "dos2unix", "source": "HOST_DIR", "file_path": "{{ pba_env_root_path }}/app/script/Images/create_image_csv.py"}     
      - {"cmd": "dos2unix", "source": "HOST_DIR", "file_path": "{{ pba_env_root_path }}/app/script/Images/Nissan_ipp_svg.py"}
      - {"cmd": "dos2unix", "source": "HOST_DIR", "file_path": "{{ pba_env_root_path }}/app/script/Images/execute_ipp.py"}
      - {"cmd": "dos2unix", "source": "HOST_DIR", "file_path": "{{ pba_env_root_path }}/app/script/Images/extractNissanCallouts.xsl"}
      - {"cmd": "dos2unix", "source": "HOST_DIR", "file_path": "{{ pba_env_root_path }}/app/script/Images/normalizeNissan.xsl"}
      
      - {"cmd": "chmod", "permissions": "775", "target": "HOST_DIR", "target_type": "FILE", "target_path": "{{ pba_env_root_path }}/app/script/GICreation.py"}
      - {"cmd": "dos2unix", "source": "HOST_DIR", "file_path": "{{ pba_env_root_path }}/app/script/GICreation.py"}
      - {"cmd": "chmod", "permissions": "775", "target": "HOST_DIR", "target_type": "FILE", "target_path": "{{ pba_env_root_path }}/app/script/move_svg_images.sh"}
      - {"cmd": "dos2unix", "source": "HOST_DIR", "file_path": "{{ pba_env_root_path }}/app/script/move_svg_images.sh"}
      
  tasks:
    
    - name: start processing 
      include_tasks: "{{ adt_code_path }}/adt_initiator.yml"   